services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:3.2
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: .
    container_name: app
    volumes:
      - .:/src
    restart: on-failure
    ports:
      - 3001:3001
    depends_on:
      - localstack
    environment:
      LOCALSTACK_HOST: localstack