service: simulation-aws-env

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: '3001'
    lambdaPort: 4001
  
functions:
  hello:
    handler: ./src/handler.run
    events:
      - httpApi:
          path: /
          method: get
